--CREATE DATABASE SISTEMA_INCIDENCIAS
USE SISTEMA_INCIDENCIAS

GO
CREATE TABLE MARCA (
	ID TINYINT PRIMARY KEY,
	NOMBRE NVARCHAR(25) NOT NULL 
) 

CREATE TABLE PROVEEDOR (
	ID TINYINT PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL ,
	DOMICILIO VARCHAR(50) NOT NULL ,
	RFC VARCHAR (15) NOT NULL 
)

CREATE TABLE TIPO_DISPOSITIVO (
	ID TINYINT PRIMARY KEY,
	NOMBRE NVARCHAR(25) NOT NULL
)


CREATE TABLE DEPARTAMENTO (
	ID TINYINT PRIMARY KEY,
	NOMBRE NVARCHAR(25) NOT NULL
)

CREATE TABLE PERSONA (
	MATRICULA INT PRIMARY KEY,
	NOMBRE VARCHAR(50),
	DOMICILIO VARCHAR(50),
	TELEFONO NUMERIC(10,0)
)

CREATE TABLE PROPIETARIO (
	PERSONA INT PRIMARY KEY FOREIGN KEY REFERENCES PERSONA (MATRICULA),
	EDIFICIO VARCHAR(10),
	AULA VARCHAR(10),
	DEPARTAMENTO TINYINT FOREIGN KEY REFERENCES DEPARTAMENTO (ID)
)

CREATE TABLE DISPOSTIVO (
	NUMERO_SERIE VARCHAR(50) PRIMARY KEY,
	PROVEEDOR TINYINT NOT NULL FOREIGN KEY REFERENCES PROVEEDOR (ID),
	FECHA_EXPIRACION_GARANTIA DATE,
	TIPO TINYINT NOT NULL FOREIGN KEY REFERENCES TIPO_DISPOSITIVO (ID),
	MODELO VARCHAR(50) NOT NULL,
	DESCRIPCION VARCHAR(50) NOT NULL,
	MARCA TINYINT NOT NULL FOREIGN KEY REFERENCES MARCA (ID),
	PROPIETARIO INT  NOT NULL FOREIGN KEY REFERENCES PROPIETARIO (PERSONA)
)

CREATE TABLE AREA_TRABAJO (
	ID TINYINT PRIMARY KEY,
	NOMBRE NVARCHAR(25) NOT NULL 
)

CREATE TABLE TECNICO (
	PERSONA INT PRIMARY KEY FOREIGN KEY REFERENCES PERSONA (MATRICULA),
	AREA_TRABAJO TINYINT NOT NULL FOREIGN KEY REFERENCES AREA_TRABAJO (ID) 
)

CREATE TABLE ESTATUS_INCIDENCIA (
	ID TINYINT PRIMARY KEY,
	NOMBRE NVARCHAR(25) NOT NULL 
)

CREATE TABLE INCIDENCIA (
	ID TINYINT PRIMARY KEY,
	REPORTADO_POR INT FOREIGN KEY REFERENCES PROPIETARIO (PERSONA) NOT NULL,
	ESTATUS TINYINT FOREIGN KEY REFERENCES ESTATUS_INCIDENCIA(ID) NOT NULL,
	FECHA_REPORTE DATE NOT NULL,
)

CREATE TABLE DETALLE_INCIDENCIA(
	INCIDENCIA TINYINT PRIMARY KEY FOREIGN KEY REFERENCES INCIDENCIA (ID) ,
	FECHA_SOLUCION DATE,
	DISPOSTIVO VARCHAR(50) FOREIGN KEY REFERENCES DISPOSTIVO (NUMERO_SERIE) NOT NULL,
	SOLUCIONADO_POR INT FOREIGN KEY REFERENCES TECNICO (PERSONA) NOT NULL,
	HORAS_TOTALES TINYINT
)
